import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter"
import { Oldenburg, Geist_Mono, Pangolin } from "next/font/google"
import { ThemeProvider } from "@mui/material/styles"
import theme from "src/theme"
import { CssBaseline } from "@mui/material"

const oldenburg = Oldenburg({
  variable: "--font-oldenburg",
  weight: "400",
})

const pangolin = Pangolin({
  variable: "--font-pangolin",
  subsets: ["latin"],
  weight: "400",
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${oldenburg.className} ${geistMono.variable} ${pangolin.variable}`}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            {children}
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
